tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
brew 'pcre2'
brew 'fish'
brew 'git'
brew 'openssl'
brew 'libevent'
brew 'lua'
brew 'readline'
brew 'tig'
brew 'tmux'
brew 'vim', args: ['with-lua']
cask 'docker'
cask 'iterm2'
cask 'vagrant'
cask 'virtualbox'
cask 'visual-studio-code'
