tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
cask "java"
cask "xquartz"
brew "fish"
brew "flow"
brew "git"
brew "gradle"
brew "heroku"
brew "node"
brew "nodenv", args: ["HEAD"]
brew "rbenv", args: ["HEAD"]
brew "reattach-to-user-namespace"
brew "tig"
brew "tmux"
brew "vim", args: ["with-lua"]
brew "watchman"
brew "wine"
brew "yarn"
cask "docker"
cask "iterm2"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
